# Generated by Django 6.0.7 on 2026-08-04 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admissions', '0006_alter_student_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='CerificateRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('TC', 'Transfer Certificate'), ('Study', 'Study Certificate')], max_length=30)),
                ('reason', models.TextField()),
                ('request_date', models.DateField(null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Issued', 'Issued')], max_length=30)),
                ('issued_date', models.DateField(null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admissions.student')),
            ],
        ),
    ]
