# Generated by Django 6.0.7 on 2026-07-28 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admissions', '0003_academicyear'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentFeeAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalfee', models.DecimalField(decimal_places=4, max_digits=10)),
                ('feepaid', models.DecimalField(decimal_places=4, max_digits=10)),
                ('feedue', models.DecimalField(decimal_places=4, max_digits=10)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admissions.academicyear')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admissions.student')),
            ],
        ),
        migrations.CreateModel(
            name='FeePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=4, max_digits=10)),
                ('payment_date', models.DateField()),
                ('payment_mode', models.CharField(choices=[('UPI', 'UPI'), ('CASH', 'CASH'), ('CARD', 'CARD'), ('BANK', 'BANK')], max_length=10)),
                ('remarks', models.CharField(max_length=1000)),
                ('student_fee_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.studentfeeaccount')),
            ],
        ),
        migrations.CreateModel(
            name='FeeStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classname', models.IntegerField()),
                ('totalfee', models.DecimalField(decimal_places=4, max_digits=10)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admissions.academicyear')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('academic_year', 'classname'), name='unique_feestructure_academicyear_classname')],
            },
        ),
        migrations.AddConstraint(
            model_name='studentfeeaccount',
            constraint=models.UniqueConstraint(fields=('student', 'academic_year'), name='unique_feeaccount_student_academic_year'),
        ),
    ]
